title:   Heting Li
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hello and welcome to my portfolio! I’m Heting Li and I'm excited to share my passion for data analysis with you and provide a glimpse into my work. I hope you enjoy exploring and getting to know me better. 
  Please take a moment to browse through my projects and feel free to contact me if you have any questions or comments.
  <br><br><br>
  <a href="https://www.linkedin.com/in/hetingli/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/kay4313/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/hetinglikay/Portfolio-Heting-Li-486fa0fdffa444909ccd013b50a39ec2?pvs=4">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
